---
dependencies:
  - role: docker-compose
  - role: bitbucket
    user_name: root
    user_home: /root
  - role: github
    user_name: root
    user_home: /root
  - role: rsync
  - role: deploy-user
    user_name: root
    user_home: /root
  - role: ssl-certificate
    ssl_domain: "{{ LAIR_NGINX_SSL_DOMAIN }}"
  - role: lair-backup
