#!/usr/bin/with-contenv bash
pid=$$

sigterm() {
  kill -INT $pid
}

trap sigterm SIGTERM

if [[ -z "$SERF_ARGS" ]]; then
  SERF_ARGS="--bind $(hostname -i) --config-file /etc/serf.conf"
fi

/usr/local/bin/serf agent $SERF_ARGS --join "$SERF_JOIN" &
pid=$!
wait
