version: "3.1"

networks:
  default:
    external:
      name: "{{ LAIR_DEPLOY_NETWORK }}"

services:

  # API
  app:
    image: alphahydrae/lair-app
    build: /var/lib/lair/backend/checkout/docker/app
    depends_on:
      - cache
      - db
    env_file:
      - .env
    environment:
      SERF_JOIN: "{{ LAIR_DEPLOY_SERF }}"
    restart: always

  # Background job processing task
  job:
    image: alphahydrae/lair-job
    build: /var/lib/lair/backend/checkout/docker/job
    env_file:
      - .env
    depends_on:
      - db
      - cache
    restart: always

  # PostgreSQL database
  db:
    image: alphahydrae/lair-db
    build: /var/lib/lair/backend/checkout/docker/db
    container_name: lair_db
    environment:
      POSTGRES_PASSWORD:
      LAIR_DATABASE_NAME:
      LAIR_DATABASE_USERNAME:
      LAIR_DATABASE_PASSWORD:
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data

  # Redis in-memory database
  cache:
    image: redis:3.2
    command: redis-server --appendonly yes
    container_name: lair_cache
    volumes:
      - cache_data:/data
    restart: always

  # Periodic backups
  backup:
    image: alphahydrae/lair-backup
    build: /var/lib/lair/backend/checkout/docker/backup
    container_name: lair_backup
    env_file:
      - .env
    depends_on:
      - cache
      - db
    restart: always
    volumes:
      - "/var/lib/lair/backend/backup:/var/lib/backup"

  # Rake task
  # This is meant to be run as a one-off task (with "run" instead of "up").
  task:
    image: alphahydrae/lair-task
    build: /var/lib/lair/backend/checkout/docker/task
    env_file:
      - .env
    restart: "no"

volumes:
  cache_data:
  db_data:
