version: "2"

networks:
  shared:
    external:
      name: "${LAIR_DEPLOY_SHARED_NETWORK}"

services:

  # Nginx web server.
  web:
    image: alphahydrae/lair-nginx
    command: /opt/lair/start.sh
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/lib/lair/public:/var/lib/lair/public"
      #- "/web/certificates/{{ LAIR_NGINX_SSL_DOMAIN }}:/web/certificates/{{ LAIR_NGINX_SSL_DOMAIN }}"
      - "/var/www/blog:/var/www/blog"
    env_file:
      - .env
    depends_on:
      - serf
    networks:
      - shared
      - default
    restart: always

  # Application in production mode.
  # The application will not serve assets.
  app:
    image: alphahydrae/lair
    volumes:
      - "/var/lib/lair/public:/usr/src/app/public"
    env_file:
      - .env
    environment:
      LAIR_LOG_TO_STDOUT: "1"
      LAIR_CONTAINER_TYPE: app
    depends_on:
      - db
      - cache
      - serf
    networks:
      - shared
      - default
    restart: always

  # Background job processing task.
  job:
    image: alphahydrae/lair
    env_file:
      - .env
    environment:
      QUEUE: "*"
      INTERVAL: "2"
      TERM_CHILD: "1"
      LAIR_LOG_TO_STDOUT: "1"
      LAIR_CONTAINER_TYPE: job
    depends_on:
      - db
      - cache
    networks:
      - default
    restart: always

  # Serf master.
  serf:
    image: alphahydrae/lair
    container_name: lair_serf
    environment:
      LAIR_CONTAINER_TYPE: serf
    networks:
      - shared
      - default
    restart: always

  # PostgreSQL database.
  db:
    image: postgres:9.5
    container_name: lair_db
    volumes:
      - "/var/lib/lair/postgresql/init-scripts:/docker-entrypoint-initdb.d"
      - "/var/lib/lair/postgresql/data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD:
      LAIR_DATABASE_NAME:
      LAIR_DATABASE_USERNAME:
      LAIR_DATABASE_PASSWORD:
    networks:
      - default
    restart: always

  # Redis in-memory database.
  cache:
    image: redis:3.2
    command: redis-server --appendonly yes
    container_name: lair_cache
    volumes:
      - "/var/lib/lair/redis/data:/data"
    networks:
      - default
    restart: always

  # Rake task.
  # This is meant to be run as a one-off task (with "run" instead of "up").
  task:
    image: alphahydrae/lair
    entrypoint: ./docker/bin/start-job.sh
    command: rake -T
    volumes:
      - "/var/lib/lair/public:/usr/src/app/public"
      - "/var/lib/lair/tmp:/usr/src/app/tmp"
    env_file:
      - .env
    networks:
      - default
    restart: "no"

  # Backup script.
  # This is meant to be run as a one-off task (with "run" instead of "up").
  backup:
    image: alphahydrae/lair-backup
    links:
      - db
      - cache
    volumes:
      - "/var/lib/lair/backup:/backup"
      - "/var/lib/lair/backup:/var/lib/lair/backup"
    env_file:
      - .env
    networks:
      - default
    restart: "no"
