development:
  bingSearch:
    url: https://api.datamarket.azure.com/Bing/Search
    rate_limit_value: 5000
    rate_limit_duration: 86400 # 1 day (in seconds)
  googleCustomSearch:
    search_engine_id: foo
    rate_limit_value: 100
    rate_limit_duration: 86400 # 1 day (in seconds)
test:
  bingSearch:
    url: http://localhost/bingSearch
    rate_limit_value: 5000
    rate_limit_duration: 86400 # 1 day (in seconds)
  googleCustomSearch:
    search_engine_id: foo
    rate_limit_value: 100
    rate_limit_duration: 86400 # 1 day (in seconds)
