development:
  bing_search:
    url: https://api.datamarket.azure.com/Bing/Search
    rate_limit_value: 5000
    rate_limit_duration: 86400 # 1 day (in seconds)
test:
  bing_search:
    url: http://localhost/bingSearch
    rate_limit_value: 5000
    rate_limit_duration: 86400 # 1 day (in seconds)
production:
  bing_search:
    url: https://api.datamarket.azure.com/Bing/Search
    rate_limit_value: 5000
    rate_limit_duration: 86400 # 1 day (in seconds)
