development:
  SearchForMissingImagesJob:
    every:
      - "10s"
    args:
      - n: 8
        interval: 1
production:
  SearchForMissingImagesJob:
    every:
      - "5m"
    args:
      - n: 4
        interval: 15
