development:
  bingSearch:
    url: <%= ENV['LAIR_BING_SEARCH_URL'] %>
    rate_limit_value: <%= ENV['LAIR_BING_SEARCH_RATE_LIMIT_VALUE'].to_i %>
    rate_limit_duration: <%= ENV['LAIR_BING_SEARCH_RATE_LIMIT_DURATION'].to_i %>
  googleCustomSearch:
    search_engine_id: <%= ENV['LAIR_GOOGLE_CUSTOM_SEARCH_ENGINE_ID'] %>
    rate_limit_value: <%= ENV['LAIR_GOOGLE_CUSTOM_SEARCH_RATE_LIMIT_VALUE'].to_i %>
    rate_limit_duration: <%= ENV['LAIR_GOOGLE_CUSTOM_SEARCH_RATE_LIMIT_DURATION'].to_i %>
  scraping:
    interval: <%= ENV['LAIR_SCRAPING_INTERVAL'].to_i %>
test:
  bingSearch:
    url: http://localhost/bingSearch
    rate_limit_value: 5000
    rate_limit_duration: 86400 # 1 day (in seconds)
  googleCustomSearch:
    search_engine_id: foo
    rate_limit_value: 100
    rate_limit_duration: 86400 # 1 day (in seconds)
  scraping:
    interval: 5
production:
  bingSearch:
    url: <%= ENV['LAIR_BING_SEARCH_URL'] %>
    rate_limit_value: <%= ENV['LAIR_BING_SEARCH_RATE_LIMIT_VALUE'].to_i %>
    rate_limit_duration: <%= ENV['LAIR_BING_SEARCH_RATE_LIMIT_DURATION'].to_i %>
  googleCustomSearch:
    search_engine_id: <%= ENV['LAIR_GOOGLE_CUSTOM_SEARCH_ENGINE_ID'] %>
    rate_limit_value: <%= ENV['LAIR_GOOGLE_CUSTOM_SEARCH_RATE_LIMIT_VALUE'].to_i %>
    rate_limit_duration: <%= ENV['LAIR_GOOGLE_CUSTOM_SEARCH_RATE_LIMIT_DURATION'].to_i %>
  scraping:
    interval: <%= ENV['LAIR_SCRAPING_INTERVAL'].to_i %>
