#!/usr/bin/with-contenv bash
pid=$$

sigterm() {
  kill -INT $pid
}

trap sigterm SIGTERM

/opt/bin/serf agent --bind $(cat /etc/hosts|grep $(hostname)|cut -f 1):7946 --config-file /etc/serf.conf &
pid=$!
wait
