echo "Creating the database user ${LAIR_DATABASE_USERNAME}"
psql -U "$POSTGRES_USER" -c "CREATE USER ${LAIR_DATABASE_USERNAME} PASSWORD '${LAIR_DATABASE_PASSWORD}'"

echo "Creating the database ${LAIR_DATABASE_NAME}"
createdb -U "$POSTGRES_USER" -O $LAIR_DATABASE_USERNAME $LAIR_DATABASE_NAME
